apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-ipallowlist
  namespace: edge
  annotations:
    meta.helm.sh/release-name: db
    meta.helm.sh/release-namespace: edge
    helm.sh/hook: "post-install,post-upgrade" # Ensures PVC creation before others
spec:
  ipAllowList:
    sourceRange:
        - 127.0.0.1/32
        - {{ .Values.edge.traefik.localIPAllowCidr }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ssl-header
  namespace: edge
  annotations:
    meta.helm.sh/release-name: db
    meta.helm.sh/release-namespace: edge
spec:
  headers:
    customRequestHeaders:
      Connection: keep-alive, Upgrade
      Upgrade: WebSocket
