apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: monitoring
type: Opaque
data:
  mariadb-root-password: {{ .Values.monitoring.mariadb.secret.mariadbRootPassword | b64enc }}
  mariadb-replication-password: {{ .Values.monitoring.mariadb.secret.mariadbReplicationpassword | b64enc }}
  mariadb-password: {{ .Values.monitoring.mariadb.secret.mariadbPassword | b64enc }}

