apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: signoz
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/renew-before: 48h
  labels:
    app: signoz
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`obs.{{ .Values.edge.domain }}` || `observability.{{ .Values.edge.domain }}` || `monitoring.{{ .Values.edge.domain }}`)
    priority: 10
    middlewares:
    - name: local-ipallowlist
      namespace: edge
    - name: ssl-header
      namespace: edge
    services:
    - kind: Service
      name: signoz
      namespace: monitoring
      passHostHeader: true
      port: 3301
      scheme: http