apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/renew-before: 48h
  labels:
    app: uptime-kuma
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`uptime.{{ .Values.edge.domain }}`)
    priority: 10
    middlewares:
    - name: local-ipallowlist
      namespace: edge
    services:
    - kind: Service
      name: uptime-kuma
      namespace: monitoring
      passHostHeader: true
      port: 3001
      scheme: http