global:
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@daily"
    keel.sh/trigger: poll

traefik:
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local # https://kubernetes.io/docs/tutorials/services/source-ip/
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  crds:
    enabled: true
  ingressClass:
    enabled: true
    isDefaultClass: true
  ports:
    web:
      port: 80
      expose:
        enabled: true
      redirectTo:
        port: websecure
    websecure:
      port: 443
      expose:
        enabled: true
  ingressRoute:
    dashboard:
      enabled: true

metallb:
  controller:
    logLevel: debug
  speaker:
    ignoreExcludeLB: true
    logLevel: debug

cert-manager:
  installCRDs: true

crowdsec:
  container_runtime: containerd
  agent:
    acquisition:
      - namespace: kube-system
        podName: traefik-*
        program: traefik
    env:
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"
  lapi:
    env:
      - name: ENROLL_KEY
        valueFrom:
          secretKeyRef:
            name: crowdsec-secret
            key: ENROLL_KEY
      - name: BOUNCER_KEY
        valueFrom:
          secretKeyRef:
            name: crowdsec-secret
            key: BOUNCER_KEY
      - name: ENROLL_INSTANCE_NAME
        value: ""
      - name: ENROLL_TAGS
        value: "secure_me"
