apiVersion: v2
name: edge
description: Helm chart for deploying kube-vip-cloudprofver, traefik, cert-manager and crowdsec
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: traefik
    version: "^28.0.0"
    repository: https://traefik.github.io/charts
  - name: cert-manager
    version: "^1.14.3"
    repository: https://charts.jetstack.io
  # - name: crowdsec
  #   version: "^0.10.0"
  #   repository: https://crowdsecurity.github.io/helm-charts
  # - name: metallb
  #   version: "^0.14.3"
  #   repository: https://metallb.github.io/metallb