apiVersion: v2
name: edge-custom
description: Helm chart for deploying storage provisioners
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: longhorn
    version: "1.7.2"
    repository: https://charts.longhorn.io