apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-ipallowlist
  namespace: edge
  annotations:
    "helm.sh/hook": "post-install,post-upgrade" # Ensures PVC creation before others
    "helm.sh/hook-weight": "-1" # Lower weight runs earlier
spec:
  ipAllowList:
    sourceRange:
        - 127.0.0.1/32
        - {{ .Values.edge.traefik.localIPAllowCidr }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ssl-header
spec:
  headers:
    customRequestHeaders:
      Connection: keep-alive, Upgrade
      Upgrade: WebSocket
