apiVersion: v1
kind: Secret
metadata:
  name: authentik-init-secret-env
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
type: Opaque
data:
  PGHOST: {{ .Values.authentik.authentik.postgresql.host | b64enc }}
  PGUSER: {{ "postgres" | b64enc }}
  PGPASSWORD: {{ .Values.persistence.postgresql.security.postgresPassword | b64enc }}
  AUTHENTIK__POSTGRES__DATABASE: {{ .Values.authentik.authentik.postgresql.name | b64enc }}
  AUTHENTIK__POSTGRES__USER: {{ .Values.authentik.authentik.postgresql.user | b64enc }}
  AUTHENTIK__POSTGRES__PASSWORD: {{ .Values.authentik.authentik.postgresql.password | b64enc }}
