apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
  labels:
    app: authentik
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`auth.{{ .Values.edge.domain }}`) ||  Host(`auth.home.{{ .Values.edge.domain }}`)
    priority: 10
    services:
    - kind: Service
      name: authentik-server
      namespace: security
      passHostHeader: true
      port: 80
      scheme: http
