apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    # TODO: Fix me
    storage: 2Gi #1800Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /share/data
    server: {{ .Values.global.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: Fix me
      storage: 2Gi #1800Gi
  volumeName: data-pv
