apiVersion: v1
kind: Secret
metadata:
  name: media-postgres-auth
  namespace: media
type: Opaque
data:
  postgres-password: {{ .Values.media.postgresql.postgres_password | b64enc }}
  password: {{ .Values.media.postgresql.postgres_mediauser_password | b64enc}}