apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-postgres-volume
  namespace: media
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      backingImage: ""
      numberOfReplicas: "1"
    volumeHandle: media-postgres-longhorn-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-postgres-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
