apiVersion: v1
kind: Service
metadata:
  name: calibre-web-automated
  labels:
    app.kubernetes.io/name: calibre-web-automated
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: calibre-web-automated
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
