apiVersion: v1
kind: Secret
metadata:
  name: calibre-web-automated-init-secret-env
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
type: Opaque
data:
  RADARR__POSTGRES__PASSWORD: {{ .Values.default.postgresql.postgresRadarrPassword | b64enc }}
  PGUSER: {{ "postgres" | b64enc }}
  PGPASSWORD: {{ .Values.default.postgresql.postgresPassword | b64enc }}
  PGHOST: {{ "persistence-postgresql.default.svc.cluster.local" | b64enc }}
  MAIN_DB: {{ "calibre-web-automated_main" | b64enc }}
  LOG_DB: {{ "calibre-web-automated_log" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: calibre-web-automated-secret-env
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
type: Opaque
data:
  RADARR__POSTGRES__PASSWORD: {{ .Values.default.postgresql.postgresRadarrPassword | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calibre-web-automated-env
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
data:
  RADARR__APP__THEME: "dark"
  # RADARR__SERVER__URLBASE: "/movies"
  RADARR__POSTGRES__HOST: {{ .Values.default.postgresql.hostnameInCluster }}
  RADARR__POSTGRES__PORT: "5432"
  RADARR__POSTGRES__MAINDB: calibre-web-automated_main
  RADARR__POSTGRES__LOGDB: calibre-web-automated_log
  RADARR__POSTGRES__USER: {{ .Values.default.postgresql.postgresRadarrUser }}
  RADARR__LOG__ANALYTICSENABLED: "false"
  RADARR__LOG__LEVEL: "INFO"
