{{- if eq .Release.Namespace "security" }}
apiVersion: v1
kind: Secret
metadata:
  name: security-postgres-auth
  namespace: security
  annotations:
    meta.helm.sh/release-name: security-persistence
    meta.helm.sh/release-namespace: security
type: Opaque
data:
  postgres-password: {{ .Values.persistence.postgresql.security.postgresPassword | b64enc }}
  password: {{ .Values.persistence.postgresql.security.postgresDefaultuserPassword | b64enc}}
{{- end }}
