apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
    - protocol: TCP
      port: 10097
      targetPort: 10097
