postgresql:
  auth:
    username: securityuser
    existingSecret: security-postgres-auth
    nameOverride: security-postgresql
    fullnameOverride: security-postgresql
  namespaceOverride: security
  primary:
    persistence:
      enabled: true
      existingClaim: security-postgres-pvc
    containerSecurityContext:
      runAsGroup: 1000
      runAsUser: 1000

# mariadb:
#   namespace: monitoring
#   auth:
#     database: 
#     existingSecret: mariadb-secret
#     user: 
#   primary:
#     persistence:
#       existingClaim: "mariadb-pvc"
