apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.edge.certificateName }}
  namespace: edge
  annotations:
    meta.helm.sh/release-name: certs
    meta.helm.sh/release-namespace: edge
spec:
  secretName: {{ .Values.edge.certificateName }}
  issuerRef:
    name: letsencrypt-staging # TODO: Use Prod later
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.edge.certificateDomain | quote }}

