apiVersion: v1
kind: Secret
metadata:
  name: radarr-init-secret-env
  namespace: media
type: Opaque
data:
  RADARR__POSTGRES__PASSWORD: {{ .Values.default.postgresql.postgresRadarrPassword | b64enc }}
  PGUSER: {{ "postgres" | b64enc }}
  PGPASSWORD: {{ .Values.default.postgresql.postgresPassword | b64enc }}
  PGHOST: {{ "persistence-postgresql.default.svc.cluster.local" | b64enc }}
  MAIN_DB: {{ "radarr_main" | b64enc }}
  LOG_DB: {{ "radarr_log" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret-env
  namespace: media
type: Opaque
data:
  RADARR__POSTGRES__PASSWORD: {{ .Values.default.postgresql.postgresRadarrPassword | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-env
  namespace: media
data:
  RADARR__APP__THEME: "dark"
  # RADARR__SERVER__URLBASE: "/movies"
  RADARR__POSTGRES__HOST: {{ .Values.default.postgresql.hostnameInCluster }}
  RADARR__POSTGRES__PORT: "5432"
  RADARR__POSTGRES__MAINDB: radarr_main
  RADARR__POSTGRES__LOGDB: radarr_log
  RADARR__POSTGRES__USER: {{ .Values.default.postgresql.postgresRadarrUser }}
  RADARR__LOG__ANALYTICSENABLED: "false"
  RADARR__LOG__LEVEL: "INFO"
