{{- if eq .Release.Namespace "default" }}
apiVersion: v1
kind: Secret
metadata:
  name: default-postgres-auth
  namespace: default
  annotations:
    meta.helm.sh/release-name: default-persistence
    meta.helm.sh/release-namespace: default
type: Opaque
data:
  postgres-password: {{ .Values.persistence.postgresql.default.postgresPassword | b64enc }}
  password: {{ .Values.persistence.postgresql.default.postgresDefaultuserPassword | b64enc}}
{{- end }}
