{{- if eq .Release.Namespace "default" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-postgres-pv
  namespace: default
  annotations:
    meta.helm.sh/release-name: default-persistence
    meta.helm.sh/release-namespace: default
spec:
  storageClassName: longhorn
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      backingImage: ""
      numberOfReplicas: "1"
    volumeHandle: default-postgres-longhorn-volume
{{- end }}
---
{{- if eq .Release.Namespace "default" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-postgres-pvc
  namespace: default
  annotations:
    meta.helm.sh/release-name: default-persistence
    meta.helm.sh/release-namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end }}
