{{- if or (eq .Values.media.platform "jellyfin") (eq .Values.media.platform "all") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
{{- end }}
