apiVersion: v2
name: security
description: Helm chart for deploying the security stack
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: authentik
    version: "2024.12.1"
    repository: https://charts.goauthentik.io
