apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: media
  labels:
    app.kubernetes.io/name: jellyseerr
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  selector:
    app.kubernetes.io/name: jellyseerr
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
