{{- if or (eq .Values.media.platform "jellyfin") (eq .Values.media.platform "all") }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
  labels:
    app: jellyseerr
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`browse.home.{{ .Values.edge.domain }}`)
    priority: 10
    middlewares:
    - name: local-ipallowlist
      namespace: edge
    services:
    - kind: Service
      name: jellyseerr
      namespace: media
      passHostHeader: true
      port: 5055
      scheme: http
{{- end }}
