apiVersion: v1
kind: Service
metadata:
  name: readarr
  namespace: media
  labels:
    app.kubernetes.io/name: readarr
spec:
  selector:
    app.kubernetes.io/name: readarr
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
