apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  storageClassName: dummy
  capacity:
    # TODO: Fix me
    storage: 2Gi #1800Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /share/data/media
    server: {{ .Values.global.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  storageClassName: dummy
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # TODO: Fix me
      storage: 2Gi #1800Gi
  volumeName: media-data-pv
