apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-external
  namespace: default
  labels:
    app: whoami-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-external
  template:
    metadata:
      labels:
        app: whoami-external
    spec:
      containers:
        - name: whoami-external
          image: traefik/whoami
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false # Prevent privilege escalation
            capabilities:
              drop: ["ALL"] # Drop all capabilities
            # runAsNonRoot: true # Ensure the container runs as non-root
            seccompProfile:
              type: RuntimeDefault # Use the default seccomp profile