apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/renew-before: 48h
  labels:
    app: longhorn-ui
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`storage.fgeck.de`)
    priority: 10
    middlewares:
    - name: local-ipallowlist
      namespace: edge
    services:
    - kind: Service
      name: longhorn-frontend
      namespace: longhorn-system
      passHostHeader: true
      port: 80
      scheme: http

