apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
  labels:
    app: sonarr
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`sonarr.home.{{ .Values.edge.domain }}`)
    priority: 10
    middlewares:
    - name: local-ipallowlist
      namespace: edge
    services:
    - kind: Service
      name: sonarr
      namespace: media
      passHostHeader: true
      port: 8989
      scheme: http
