apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app.kubernetes.io/name: plex
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: plex
  ports:
    - port: 32400
      targetPort: 32400
      protocol: TCP
      name: pms
