apiVersion: v1
kind: Secret
metadata:
  name: plex-secret-env
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
type: Opaque
data:
  PLEX_CLAIM: {{ .Values.media.plex.claim | b64enc }}