apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: '@daily'
    keel.sh/trigger: poll
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
  labels:
    app.kubernetes.io/name: plex
  name: plex
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
      annotations:
        meta.helm.sh/release-name: media
        meta.helm.sh/release-namespace: media
    spec:
      automountServiceAccountToken: false
      containers:
      - name: main
        env:
        - name: TZ
          value: Europe/Berlin
        - name: HOSTNAME
          value: "PlexServer"
        - name: PLEX_UID
          value: "1000"
        - name: PLEX_GID
          value: "1000"
        envFrom:
        - secretRef:
            name: plex-secret-env
        image: index.docker.io/plexinc/pms-docker:1.41.3.9314-a0bfb8370
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 32400
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
        # securityContext:
          # runAsGroup: 1000
          # runAsNonRoot: true
          # runAsUser: 1000
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /identity
            port: 32400
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: plex-config
        - mountPath: /transcode
          name: plex-transcode
        - mountPath: /data
          name: data
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: plex-transcode-pvc
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc
