{{- if or (eq .Values.media.platform "plex") (eq .Values.media.platform "all") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-pv
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      backingImage: ""
      numberOfReplicas: "1"
    volumeHandle: overseerr-longhorn-volume
{{- end }}
---
{{- if or (eq .Values.media.platform "plex") (eq .Values.media.platform "all") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-pvc
  namespace: media
  annotations:
    meta.helm.sh/release-name: media
    meta.helm.sh/release-namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: overseerr-pv
{{- end }}
