apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-backup-secret
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
type: Opaque
data:
  DB_TYPE: {{ printf "postgresql" | b64enc }}
  PG_HOST: {{ .Values.persistence.postgresql.security.host | b64enc }}
  PG_PORT: {{ .Values.persistence.postgresql.security.port | b64enc }}
  PG_DBNAME: {{ .Values.persistence.postgresql.security.postgresVaultwardenDatabase | b64enc }}
  PG_USERNAME: {{ .Values.persistence.postgresql.security.postgresVaultwardenUser | b64enc }}
  PG_PASSWORD: {{ .Values.persistence.postgresql.security.postgresVaultwardenPassword | b64enc }}
  ZIP_PASSWORD: {{ .Values.vaultwarden.backup.zipPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-rclone-secret
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
data:
  rclone.conf: {{ printf "[BitwardenBackup]\ntype = drive\nscope = drive\nteam_drive =\nclient_id = %s\nclient_secret = %s\ntoken = %s\n" .Values.vaultwarden.backup.client_id .Values.vaultwarden.backup.client_secret .Values.vaultwarden.backup.token | b64enc }}
