apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-init-secret-env
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
type: Opaque
data:
  PGHOST: {{ .Values.persistence.postgresql.security.host | b64enc }}
  PGUSER: {{ "postgres" | b64enc }}
  PGPASSWORD: {{ .Values.persistence.postgresql.security.postgresPassword | b64enc }}
  VAULTWARDEN__POSTGRES__DATABASE: {{ .Values.persistence.postgresql.security.postgresVaultwardenDatabase | b64enc }}
  VAULTWARDEN__POSTGRES__USER: {{ .Values.persistence.postgresql.security.postgresVaultwardenUser | b64enc }}
  VAULTWARDEN__POSTGRES__PASSWORD: {{ .Values.persistence.postgresql.security.postgresVaultwardenPassword | b64enc }}
