apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`vw.{{ .Values.edge.domain }}`) && PathPrefix(`/`) || Host(`vw.home.{{ .Values.edge.domain }}`) && PathPrefix(`/`)
    priority: 10
    services:
    - kind: Service
      name: vaultwarden
      namespace: security
      passHostHeader: true
      port: 8080
      scheme: http
  - kind: Rule
    match: Host(`vw.{{ .Values.edge.domain }}`) && Path(`/notifications/hub`) || Host(`vw.home.{{ .Values.edge.domain }}`) && Path(`/notifications/hub`)
    services:
    - kind: Service
      name: vaultwarden
      namespace: security
      passHostHeader: true
      port: 3012
