apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.vaultwarden.admin_token | b64enc }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.persistence.postgresql.security.postgresVaultwardenUser .Values.persistence.postgresql.security.postgresVaultwardenPassword .Values.persistence.postgresql.security.host .Values.persistence.postgresql.security.port .Values.persistence.postgresql.security.postgresVaultwardenDatabase | b64enc }}
