apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: security
  annotations:
    meta.helm.sh/release-name: security
    meta.helm.sh/release-namespace: security
    "helm.sh/hook": "post-install,post-upgrade"
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  selector:
    app.kubernetes.io/name: vaultwarden
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: websockets
      protocol: TCP
      port: 3012
      targetPort: 3012
