apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: default
  annotations:
    meta.helm.sh/release-name: apps
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      backingImage: ""
      numberOfReplicas: "1"
    volumeHandle: portainer-longhorn-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: default
  annotations:
    meta.helm.sh/release-name: apps
    meta.helm.sh/release-namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: portainer-pv
