apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: default
  annotations:
    meta.helm.sh/release-name: apps
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/name: portnainer
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`port.home.{{ .Values.edge.domain }}`)
    priority: 10
    services:
    - kind: Service
      name: portainer
      namespace: default
      passHostHeader: true
      port: 9000
      scheme: http
