apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr
  namespace: media
  labels:
    app: overseerr
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`browse.{{ .Values.edge.domain }}`)
    priority: 10
    middlewares:
    services:
    - kind: Service
      name: overseerr
      namespace: media
      passHostHeader: true
      port: 5055
      scheme: http
