scriptConfigs:
  clusterName: ""
  gateway: ""
  finalControlPlaneIp: ""
  finalWorkerIp: ""
  currentControlPlaneIp: ""
  currentWorkerIp: ""

bootstrap:
  ip_ranges:
    range_default: ""
    cidr_edge: ""

edge:
  certificateName: ""
  certificateDomain: ""
  letsencrypt:
    email: ""
  cloudflare_api_key: ""
  traefik:
    localIPAllowCidr: ""


traefik:
  tlsStore:
    default:
      defaultCertificate:
        secretName: ""
