scriptConfigs:
  clusterName: ""
  gateway: ""
  finalControlPlaneIp: ""
  finalWorker1Ip: ""
  finalWorker2Ip: ""
  currentControlPlaneIp: ""
  currentWorker1Ip: ""
  currentWorker2Ip: ""

global:
  nfs:
    server: ""

bootstrap:
  ip_ranges:
    range_default: ""
    cidr_edge: ""

storage:
  longhorn:
    smb:
      server: ""
      username: ""
      password: ""

edge:
  domain: 
  certificateName: ""
  certificateDomain: ""
  letsencrypt:
    email: ""
  dyndns:
    user: ""
    password: ""
  cloudflare:
    apiKey: ""
    email: ""
  traefik:
    localIPAllowCidr: ""

traefik:
  tlsStore:
    default:
      defaultCertificate:
        secretName: ""

monitoring:
  mariadb:
    secret:
      mariadbRootPassword: ""
      mariadbReplicationpassword: ""
      mariadbPassword: ""

default:
  postgresql:
    hostnameInCluster: ""
    postgresPassword: ""
    postgresUser: ""
    postgresDefaultuserPassword: ""
    postgresRadarrUser: ""
    postgresRadarrPassword: ""
    postgresSonarrUser: ""
    postgresSonarrPassword: ""
    postgresReadarrUser: ""
    postgresReadarrPassword: ""

media:
  readarr:
    apiKey: ""
  plex:
    claim:  ""
