scriptConfigs:
  clusterName: ""
  gateway: ""
  finalControlPlaneIp: ""
  finalWorker1Ip: ""
  finalWorker2Ip: ""
  currentControlPlaneIp: ""
  currentWorker1Ip: ""
  currentWorker2Ip: ""
  vaultwardenURL: ""

global:
  nfs:
    server: ""

bootstrap:
  ip_ranges:
    range_default: ""
    cidr_edge: ""

storage:
  longhorn:
    smb:
      server: ""
      username: ""
      password: ""

edge:
  domain: ""
  certificateName: ""
  certificateDomain: ""
  letsencrypt:
    email: ""
  dyndns:
    fritzboxPollURL: ""
    user: ""
    password: ""
  cloudflare:
    apiKey: ""
    email: ""
  traefik:
    localIPAllowCidr: ""
    gatewayCidr: ""

traefik:
  tlsStore:
    default:
      defaultCertificate:
        secretName: ""

monitoring:
  mariadb:
    secret:
      mariadbRootPassword: ""
      mariadbReplicationpassword: ""
      mariadbPassword: ""

persistence:
  postgresql:
    default:
      host: ""
      host: ""
      postgresPassword: ""
      postgresUser: ""
      postgresDefaultuserPassword: ""
      postgresRadarrUser: ""
      postgresRadarrPassword: ""
      postgresSonarrUser: ""
      postgresSonarrPassword: ""
      postgresReadarrUser: ""
      postgresReadarrPassword: ""
    security:
      host: ""
      port: "5432"
      postgresPassword: ""
      postgresUser: ""
      postgresDefaultuserPassword: ""
      postgresAuthentikUser: ""
      postgresAuthentikPassword: ""
      postgresVaultwardenDatabase: "vaultwarden"
      postgresVaultwardenUser: ""
      postgresVaultwardenPassword: ""

authentik:
  authentik:
    secret_key: ""
    # must match values in persistence.postgresql.security.*
    postgresql:
      host: ""
      name: ""
      user: ""
      password: ""

vaultwarden:
  admin_token: ""
  backup:
    zipPassword: ""
    client_id: ""
    client_secret: ""
    token: ""

media:
  readarr:
    apiKey: ""
  plex:
    claim:  ""
